[plugin]
name = "dokku-shoreman"
description = "A plugin for dokku that injects a stripped down version of shoreman"
version = "0.2.1"
website_url = "https://github.com/GeoCENS/dokku-shoreman"
[plugin.config]
